### PR TITLE
Added, share folder permissions to 777 so that apache can write files

### PR DESCRIPTION
**Pull request by ssheduardo**
For example to Magento is necessary.

### CODE REVIEW

**Comment by ssheduardo** [comment]
STOP!!!, I found one error the permission. when executed composer or other command of type (gulp, bower, etc.)
Not applied the pull request.

**Comment by SidiGi** [comment]
Yeah! I think something wrong in it

**Comment by ssheduardo** [comment]
Please help for set folder permissions to 777.

**Comment by ssheduardo** [comment]
Correctly assigned route and permissions, please try.

**Comment by SidiGi** [comment]
You can make this changes manualy

**Pull request closed without merging**
